### ISSUE TITLE
Withdrawal can not be proved Error

### ISSUE THREAD

**Issue by Danijel-Enoch** [base-org/withdrawer#5]
The latest L2 output is 2233800 and is not past L2 block 2235640 that includes the withdrawal, no withdrawal can be proved yet.
Please wait for the next proposal submission to 0x56315b90c40730925ec5485cf004d835058518A0, which happens every 30m0s.

Pls what causes this error?

Could it the RPC URL?

**Comment by mdehoog** [comment]
Output proposals are written once every hour. Unfortunately the error message was misreporting this to say "every 30m0s". This is fixed with commit d960e2f00f9159434a9882d05269505b14a6050a.

Because output proposals are submitted to the L1 every 60m, it can take up to an hour to prove the withdrawal. This is expected.
